-- VHDL Entity MIPS.MIPS_tester.interface
--
-- Created:
--          by - kolaman.UNKNOWN (KOLAMAN-PC)
--          at - 09:22:44 17/02/2013
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2011.1 (Build 18)
--
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;

ENTITY MCU_tester IS
	PORT( clock				: OUT 	STD_LOGIC; 
		Switches			: OUT 	STD_LOGIC_VECTOR( 9 DOWNTO 0 );
		Keys				: OUT 	STD_LOGIC_VECTOR( 3 DOWNTO 0 );
		LEDGreen			: IN	STD_LOGIC_VECTOR( 7 DOWNTO 0 );
		LEDRed				: IN	STD_LOGIC_VECTOR( 7 DOWNTO 0 );
		HEX0				: IN 	STD_LOGIC_VECTOR(6 downto 0);
		HEX1				: IN 	STD_LOGIC_VECTOR(6 downto 0);
		HEX2				: IN 	STD_LOGIC_VECTOR(6 downto 0);
		HEX3				: IN 	STD_LOGIC_VECTOR(6 downto 0));

-- Declarations

END MCU_tester ;

--
-- VHDL Architecture MIPS.MIPS_tester.struct
--
-- Created:
--          by - kolaman.UNKNOWN (KOLAMAN-PC)
--          at - 09:22:44 17/02/2013
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2011.1 (Build 18)
--
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;


ARCHITECTURE struct OF MCU_tester IS

   -- Architecture declarations

   -- Internal signal declarations


   -- ModuleWare signal declarations(v1.9) for instance 'U_0' of 'clk'
   SIGNAL mw_U_0clk : std_logic;
   SIGNAL mw_U_0disable_clk : boolean := FALSE;

   -- ModuleWare signal declarations(v1.9) for instance 'U_1' of 'pulse'
 --  SIGNAL mw_U_1pulse : std_logic :='0';


BEGIN

   -- ModuleWare code(v1.9) for instance 'U_0' of 'clk'
   u_0clk_proc: PROCESS
   BEGIN
      WHILE NOT mw_U_0disable_clk LOOP
         mw_U_0clk <= '0', '1' AFTER 50 ns;
         WAIT FOR 100 ns;
      END LOOP;
      WAIT;
   END PROCESS u_0clk_proc;
   mw_U_0disable_clk <= TRUE AFTER 100000 ns;
   clock <= mw_U_0clk;

   -- ModuleWare code(v1.9) for instance 'U_1' of 'pulse'
 --  reset <= mw_U_1pulse;
--   u_1pulse_proc: PROCESS
--   BEGIN
--      mw_U_1pulse <= 
--         '0',
--         '1' AFTER 20 ns,
--         '0' AFTER 120 ns,
--		 '1' AFTER 20 ns;
--      WAIT;
--    END PROCESS u_1pulse_proc;

	gen_clk1 : process
        begin
		Switches <= "1000001010";
		Keys <= "1111";
		wait for 20 ns;
			Keys <= "1110";
		wait for 120 ns;
			Keys(0) <= '1';
		wait for 9820 ns;
			Keys(3) <= '0';
			--Switches <= "0000001010";
		wait for 100 ns;
			Keys(3) <= '1';
			--Switches <= "1000001010";
		wait for 6820 ns;
			--Keys(2) <= '0';
			Switches <= "0000001010";
		wait for 2000 ns;
			--Keys(2) <= '1';
			Switches <= "1000001010";
		--wait for 2000 ns;
		--	Keys(2) <= '1';
		--wait for 100 ns;
		--	Keys(2) <= '0';
		wait;
      end process;

   -- Instance port mappings.

END struct;
